services:
  lr-webchat-go:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - PORT=4000
  lr-webchat-react:
    build:
      context: ../../lr_webchat
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      lr-webchat-go:
        condition: service_started
